import { HeartIcon, ShoppingCartIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'
import React, { useState } from 'react'
import All from '../../components/All'
import Footer from '../../components/Footer'
import Computing from '../../components/Computing'
import Header from '../../components/Header'
import { computers, smartphones, electronics } from '../../utiles/data'
import axios from "axios"
import { useRouter } from "next/router"
import Image from "next/image"

const category = ({ category, categories, subcats }) => {
  const [openCatModal, setOpenCatModal] = useState(false)
  const handleAll = () => {
        setOpenCatModal(prev => !prev)
    }
    const router = useRouter()
    // // const {pathname} = useRouter()
    // const path = router.pathname
     console.log({category})
     console.log({categories})
     console.log({subcats})
  return (
      <section className="head_section">
      <Head>
        <title>Wave | {category.description}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        {openCatModal && <All />}
        <Header setOpenCatModal={setOpenCatModal} handleAll={handleAll} />
      <div className="main_grid">
          <span className="col-span-8 flex-col gap-y-2">
            <p className="text-4xl font-extrabold text-black"> {category.name}</p>
            <p className="text-sm font-light text-slate-700">{category.description}</p>
          </span>
          <span className="col-span-4 ">
            <img src={category.descriptionImg} alt="smart_phones" className="object-fit w-1/2 h-1/5" />
          </span> 
        </div>
        <div className="cat_grid_div">
          {subcats?.map(item => (
            <div onClick={() => router.push(`/subcategories/${item._id}`)} key={item._id} className="main_grid_div">
              <img src={item.img} alt="" className=" object-contain" />
              <span className="h-28 w-28 relative">
                    <Image src={item.image} alt="alt_image" layout="fill" className="img_tag object-contain"/>
                </span>
              <p className="text-sm text-gray-800 font-bold">{item.name}</p>
            </div>
            ))}
         </div>
        <Computing categories={categories} />
      </main>
      <Footer />
    </section>
  )
}

export async function getServerSideProps({params}) {
    const { id } = params
    const category = await axios(`http://localhost:8000/api/categories/getCategory/${id}`).then((res) => res.data)
    const categories = await axios("http://localhost:8000/api/product/fetchAll").then((res) => res.data)
    const subcats = await axios(`http://localhost:8000/api/categories/getSubCategoryFromCat/${id}`).then((res) => res.data)
    return {
        props: {
            category: category?.category,
            categories: categories.data,
            subcats: subcats?.data
            // topBrands
        }
    }
}

export default category
// http://localhost:8000/api/categories/getSubCategories