import { HeartIcon, ShoppingCartIcon, checkCircleIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'
import React, { useState } from 'react'
import All from '../../components/All'
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import { electronics, products } from '../../utiles/data'
import { useDispatch } from "react-redux"
import { addToCart } from "../../slices/cartSlice.js"
import axios from "axios"
import Image from "next/image"
import { useRouter } from "next/router"
const Product = ({ single }) => {
    const [openCatModal, setOpenCatModal] = useState(false)
    const handleAll = () => {
        setOpenCatModal(prev => !prev)
    }
    const router = useRouter()
    const dispatch = useDispatch()
    const { photo, title, disc, category, _id, price, name, desc } = single.data
      const product = {
        title, photo, _id, category, desc, price 
      }
      
    // console.log(single)
  return (
    <section className="head_section">
      <Head>
        <title>Wave | Shop the lattest quality home appliances from our trusted dealers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        {openCatModal && <All />}
        <Header setOpenCatModal={setOpenCatModal} handleAll={handleAll} />
      <section className="grid grid-cols-12 lg:gap-x-4 gap-y-4 rounded-sm px-4 lg:px-20 mx-auto my-6">
        <div className="col-span-12 lg:col-span-9 flex items-center rounded-sm bg-white p-4">
            <div className="grid grid-cols-12 gap-x-4">
              {/* img */}
                <div className="col-span-12 lg:col-span-4 flex space-y-6 flex-col w-full">
                    <span className="h-32 lg:h-56 h-20 w-32 lg:w-56 relative">
                        <Image src={photo} alt="alt_image" layout="fill" className="img_tag object-contain"/>
                    </span>
                        {/*</div>    */}
                    {/*</span>*/}
                    <span className="flex space-x-1 h-10 w-full">
                        {electronics?.map((item, i) => (
                         <img key={_id} src={photo} alt="" className="h-full w-14 object-contain border cursor-pointer border-orange-300 rounded-md" />
                        ))}
                    </span>
                </div>
                {/*  */}
                <div className="col-span-12 lg:col-span-8 flex flex-col space-y-3 my-3">
                    <span className="flex flex-col">
                       <p className="text-sm text-semibold text-gray-900">{title}</p>
                       <p className="text-xs text-gray-500">Category: {category}</p>
                       <p className="text-xs text-gray-500">Search from similar category bg-orange-400 px-4 py-2 rounded-sm text-white text-sm font-semibold flex justify-between items-center</p>
                    </span>
                    <span className="flex flex-col">
                        <h3 className="text-2xl text-bold text-gray-800">Ksh. {price}</h3>
                        <h3 className="text-xs font-normal text-gray-600">More products from this seller</h3>
                        <h3 className="text-xs font-normal text-gray-600">Rating 2.1 (4,456)</h3>
                    </span>
                    <span className="flex space-x-4 items-center">
                        <button onClick={() => dispatch(addToCart(product))} className="bg-orange-400 px-4 py-2 w-max-w-fit rounded-sm text-white text-sm font-semibold flex justify-between items-center">
                            Add to Cart <ShoppingCartIcon className="h-6 w-6 text-white ml-4" />
                        </button>
                        <HeartIcon className="h-6 w-6 text-orange-400"/>
                    </span>
                </div>
            </div>
        </div>
        <div className="col-span-12 lg:col-span-3 flex-col space-y-4 rounded-sm bg-white p-4">
            {/*<p className="text-sm font-bold text-black">{desc}</p>*/}
            <p className="text-sm font-bold text-black">Blue jacket suitable for rainy season</p>
        </div>
        </section>
        <section className="grid grid-cols-12 bg-transparent px-4 lg:px-20">
          <div className="col-span-12 lg:col-span-9 flex flex-col gap-y-6">
            <div className="flex flex-col border-b border-gray-300">
              <p className="text-sm font-normal text-gray-600">Reviews</p>
              <span className="flex-col flex space-y-3">
                <h2 className="text-lg lg:text-3xl font-semibold lg:font-extrabold text-black">{title}</h2>
                <h2 className="text-sm font-normal text-gray-500">Nairobi</h2>
                 <h3 className="text-lg lg:text-5xl text-normal lg:text-semibold text-orrange-500">Ksh. {price}</h3>
                 <p className="text-sm text-gray-600 font-normal leading-8">{desc}.</p>
              </span>
            </div>
            <div className="flex flex-col border-b border-gray-300">
              <p className="text-3xl font-semibold text-gray-700">Specifications</p>
              <span className="flex-col flex space-y-3">
                 <p className="text-sm text-gray-600 font-normal leading-6">{desc}.</p>
              </span>
            </div>
            <div className="flex flex-col border-b border-gray-300">
              <p className="text-lg lg:text-3xl font-semibold text-gray-700">Reviews</p>
              <span className="flex-col flex space-y-3">
                 <p className="text-sm text-gray-600 font-normal leading-6">Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Pellentesque in ipsum id orci porta dapibus.Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Sed porttitor lectus nibh.Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Curabitur aliquet quam id dui posuere blandit.Proin eget tortor risus. Cras ultricies ligula sed magna dictum porta.Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Pellentesque in ipsum id orci porta dapibus.</p>
              </span>
            </div>
            <div className="col-span-3 flex flex-col gap-y-6"></div>
          </div>
        </section>
    </main>
    <Footer />
    </section>
  )
}

export const getServerSideProps = async ({params}) => {
    const { id } = params
    // const product = await axios("http://localhost:8000/api/product/fetchAll").then((res) => res.json())
    const single = await axios(`http://localhost:8000/api/product/fetch/${id}`).then((res) => res.data);
    
    return {
        props: {
            // product,
            single
        }
    }
}

export default Product