import Head from 'next/head'
import { useState } from 'react'
import All from '../components/All'
import Categories from '../components/Categories'
import GreatDeals from '../components/GreatDeals'
import Header from "../components/Header"
import Slide from '../components/Slide'
import TopBrands from '../components/TopBrands'
import RecentProducts from '../components/RecentProducts'
import Footer from '../components/Footer'
import { slide } from '../utiles/data'
import axios from 'axios'

const Home = ({ greatDeals, recentProducts, categories }) => {
  const [openCatModal, setOpenCatModal] = useState(false)
    const handleAll = () => {
        setOpenCatModal(prev => !prev)
    }
    console.log(categories)
    // console.log({subcategories})
  return (
    <div className="head_section">
      <Head>
        <title>Wave | Online shopping. Shop groceries, electronics, apparels, machineries, utensils, office equipment, furniture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        {openCatModal && <All />}
        <Header  handleAll={handleAll} />
        <Slide slide={ slide }/>
        <TopBrands />
        <Categories categories={categories} />
        <RecentProducts recentProducts={recentProducts} />
        <GreatDeals greatDeals={greatDeals} />
      </main>
      <Footer />
    </div>
  )
}

export async function getServerSideProps({params}) {
    // const { id } = params
    const greatDeals = await axios("http://localhost:8000/api/product/fetchAll").then((res) => res.data)
    const recentProducts = await axios("http://localhost:8000/api/product/fetchAll?new=true").then((res) => res.data)
    const categories = await axios("http://localhost:8000/api/categories/getCategories").then((res) => res.data)
    // const categories = await axios("http://34.125.251.214:8081/category/all").then((res) => res.data)
    return {
        props: {
            recentProducts,
            greatDeals,
            categories: categories?.data,
        }
    }
}

export default Home
