import { CheckCircleIcon, checkBadgeIcon, EyeIcon, EyeSlashIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'
import React, { useState } from 'react'
import { useRouter } from "next/router"

const Login = () => {
	const router = useRouter()
    const [toggle, setToggle] = useState(false)
    const handleToggle = () => {
        setToggle(prev => !prev)
    }
    return (
        <div className="head_section">
          {/* <Html> */}
            <Head>
                <title>Wave | Online shopping. Shop groceries, electronics, apparels, machineries, utensils, office equipment, furniture</title>
                <meta name="description" content="Generated by create next app" />
          //   <link rel="preconnect" href="https://fonts.googleapis.com" />
          // <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          // <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700&display=swap" rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
          {/* </Html> */}
            <main className="main">
                <section className="login_grid">
                     {/*grid - 1*/}
                    <div className="flex flex-col space-y-6 shadow-md shadow-white rounded-md bg-white px-6 lg:px-20 py-10 md:w-1/2 w-4/5 mx-auto">
                        <p className="register_header">
                            Sign in to your Wave account
                        </p>
                        <form className="flex flex-col space-y-4 w-full max-h-fit">
                            <label className="label_text">Email:</label>
                            <span className="form_span border">
                                <input type="text" name="email" placeholder="example@gmail.com" className="form_input" id="email" />
                            </span>
                            <label className="label_text">Password:</label>
                            <span className="form_span flex items-center justify-between border">
                                <input type={ toggle ? "text" : "password" } name="password" placeholder="" className="form_input" id="password" />
                                { !toggle ? <EyeIcon onClick={handleToggle} className="icon_grid cursor-pointer" /> : <EyeSlashIcon onClick={handleToggle} className="icon_grid cursor-pointer" />}
                            </span>
                        </form>
                        <div className="flex flex-col space-y-6 my-12 items-center">
                    {/*check-box*/}
                            <div className="flex space-x-2">
                                <span className="flex">
                                    <CheckCircleIcon className="icon_grid"/>
                                </span>
                                <span className="flex flex-col space-y-2">
                                    <p className="register_text">Get emails from Wave about product updates, industry news, and events. If you change your mind, you can unsubscribe at any time.</p>
                                    <p className="text-sm font-normal text-orange-400 cursor-pointer">Privacy Policy</p>
                                </span>
                            </div>
                            <button type="submit" className="sign_up_button">Login</button>
                            <p className="text-sm font-normal text-orange-400 cursor-pointer">Forgot Password?</p>
                            <p className="text-sm font-normal text-gray-800">Don't have an account? <span onClick={() => router.push("/register")} className="text-orange-400 cursor-pointer">Sign Up</span></p>
                        </div>
                    </div>
                </section>
            </main>
          {/*<Footer />*/}
        </div>
    )
}

export default Login